volumes:
  db_data:
    driver: local
    external: false

networks:
  internal:
    external: false

services:
  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - "127.0.0.1:27017:27017"
    networks:
      - "internal"
    volumes:
      - "db_data:/data/db"
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=root"
      - "MONGO_INITDB_ROOT_PASSWORD=password"

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - "127.0.0.1:8081:8081"
    networks:
      - "internal"
    environment:
      - "ME_CONFIG_MONGODB_ADMINUSERNAME=root"
      - "ME_CONFIG_MONGODB_ADMINPASSWORD=password"
      - "ME_CONFIG_MONGODB_URL=mongodb://root:password@mongo:27017/"
      - "ME_CONFIG_BASICAUTH=false"
    depends_on:
      - "mongo"
